///| Canonical Git object/domain types.

///|
pub type ObjectId = @object.ObjectId

///|
pub type ObjectType = @object.ObjectType

///|
pub type GitError = @object.GitError

///|
pub type TreeEntry = @object.TreeEntry

///|
pub type Commit = @object.Commit

///|
pub type PackObject = @object.PackObject

///|
pub type PackDeltaMode = @object.PackDeltaMode

///|
pub type PackCompression = @object.PackCompression

///|
pub type Sha1State = @object.Sha1State
